development:
  database: newdb
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: newdb_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
